  to: 'sp@gmail.com',
  from: { email: 'postmaster@wajooba.com', name: 'Pankaj' },
  dynamic_template_data: {
    subject: 'Partial Payment Invoice',
    logoUrl: undefined,
    tenantEmail: 'pankajnale.nityaobject@gmail.com',
    tenantName: 'Pankaj',
    tenantAddress: '',
    tenantPhone: '+1-5555555555',
    name: 'sp sp',
    templateId: 'invoice_partial',
    amountPaid: 15,
    generatedAt: 'Mon Aug 08 2022 5:30 am',
    currency: '$',
    invoiceDate: 'Mon Jul 04 2022 5:30 am',
    time: '5:30 am',
    items: [ [Object] ],
    total: 15,
    subtotal: 15,
    cardFees: 0,
    tax: 0,
    balance: 0,
    _id: '62c1f175050c0721b4a15da9',
    invoiceId: '1279067',
    invoiceName: 'Payment Testing Course/recurring',
    contactId: 'WMdjWkvGrb',
    contactEmail: 'sp@gmail.com',
    contactName: '',
    contactPhone: '',
    salesPersonId: '20689',
    salesPersonName: 'Wajooba',
    salesPersonEmail: 'wajooba@gmail.com',
    salesPersonPhoneNo: '',
    orgId: 'pankajtest5',
    tenantId: 'ga8ADXEAOW',
    isDeleted: undefined,
    payments: [ [Object] ],
    refunds: [],
    subTotal: 15,
    notes: 'this is a sampel note while checkout',
    status: 'partial',
    contactCard: undefined,
    promiseAmount: 0,
    promiseNotes: '',
    subscriptionAmount: 0,
    additionalInfo: 'GSTIN'
  },
  templateId: 'd-2ba5cc0e4c914a579621e457798835a7'
}
PAYLOAD: {
  to: [ 'wajooba@gmail.com', 'parthtest@mailinator.com' ],
  from: { email: 'postmaster@wajooba.com', name: 'Wajooba' },
  dynamic_template_data: {
    subject: 'Yippe! Partial payment received from sp sp!',
    logoUrl: undefined,
    adminList: [ [Object], [Object] ],
    tenantEmail: 'pankajnale.nityaobject@gmail.com',
    tenantName: 'Pankaj',
    tenantAddress: '',
    tenantPhone: '+1-5555555555',
    name: 'sp sp',
    templateId: 'invoice_notify_admin',
    amountPaid: 15,
    generatedAt: 'Mon Aug 08 2022 5:30 am',
    currency: '$',
    invoiceDate: 'Mon Jul 04 2022 5:30 am',
    time: '5:30 am',
    items: [ [Object] ],
    total: 15,
    subtotal: 15,
    cardFees: 0,
    tax: 0,
    balance: 0,
    _id: '62c1f175050c0721b4a15da9',
    invoiceId: '1279067',
    invoiceName: 'Payment Testing Course/recurring',
    contactId: 'WMdjWkvGrb',
    contactEmail: 'sp@gmail.com',
    contactName: '',
    contactPhone: '',
    salesPersonId: '20689',
    salesPersonName: 'Wajooba',
    salesPersonEmail: 'wajooba@gmail.com',
    salesPersonPhoneNo: '',
    orgId: 'pankajtest5',
    tenantId: 'ga8ADXEAOW',
    isDeleted: undefined,
    payments: [ [Object] ],
    refunds: [],
    subTotal: 15,
    notes: 'this is a sampel note while checkout',
    status: 'partial',
    contactCard: undefined,
    promiseAmount: 0,
    promiseNotes: '',
    subscriptionAmount: 0,
    additionalInfo: 'GSTIN'
  },
  templateId: 'd-da943571b444403c9048531ce77af7b5'
}